# Generated by Django 5.1 on 2024-08-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='m1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='foto/')),
                ('texto1', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='m',
        ),
    ]
